import { Lead } from './lead';

export const LEAD_MOCK_DATA: Lead[] = [
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    status: 'Interviewed',
    phone: '555-555-1234',
    currentCompany: 'Smith Ltd',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 3,
    skills: ['React', 'TypeScript', 'Redux'],
    resumeUrl: 'https://example.com/resume/janesmith.pdf',
  },
  {
    id: 3,
    name: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    status: 'Qualified',
    phone: '555-555-9876',
    currentCompany: 'Johnson LLC',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 7,
    skills: ['Python', 'Django', 'PostgreSQL'],
    resumeUrl: 'https://example.com/resume/michaeljohnson.pdf',
  },
  {
    id: 4,
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    status: 'New',
    phone: '555-555-4567',
    currentCompany: 'Davis Group',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 2,
    skills: ['Java', 'Spring Boot', 'REST APIs'],
    resumeUrl: 'https://example.com/resume/emilydavis.pdf',
  },
  {
    id: 5,
    name: 'Robert Brown',
    email: 'robert.brown@example.com',
    status: 'Interviewed',
    phone: '555-555-6543',
    currentCompany: 'Brown Inc.',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 4,
    skills: ['C++', 'Linux', 'Qt'],
    resumeUrl: 'https://example.com/resume/robertbrown.pdf',
  },
  {
    id: 6,
    name: 'Jessica Williams',
    email: 'jessica.williams@example.com',
    status: 'Qualified',
    phone: '555-555-7890',
    currentCompany: 'Williams Co.',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 6,
    skills: ['Ruby', 'Rails', 'JavaScript'],
    resumeUrl: 'https://example.com/resume/jessicawilliams.pdf',
  },
  {
    id: 7,
    name: 'David Miller',
    email: 'david.miller@example.com',
    status: 'New',
    phone: '555-555-3210',
    currentCompany: 'Miller Solutions',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 5,
    skills: ['Go', 'Microservices', 'Kubernetes'],
    resumeUrl: 'https://example.com/resume/davidmiller.pdf',
  },
  {
    id: 8,
    name: 'Laura Wilson',
    email: 'laura.wilson@example.com',
    status: 'Interviewed',
    phone: '555-555-4321',
    currentCompany: 'Wilson Enterprises',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 3,
    skills: ['PHP', 'Laravel', 'MySQL'],
    resumeUrl: 'https://example.com/resume/laurawilson.pdf',
  },
  {
    id: 9,
    name: 'Daniel Moore',
    email: 'daniel.moore@example.com',
    status: 'Qualified',
    phone: '555-555-8765',
    currentCompany: 'Moore Industries',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 6,
    skills: ['React', 'Node.js', 'GraphQL'],
    resumeUrl: 'https://example.com/resume/danielmoore.pdf',
  },
  {
    id: 10,
    name: 'Sophia Taylor',
    email: 'sophia.taylor@example.com',
    status: 'New',
    phone: '555-555-9875',
    currentCompany: 'Taylor & Co.',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 2,
    skills: ['Python', 'Flask', 'SQLAlchemy'],
    resumeUrl: 'https://example.com/resume/sophiataylor.pdf',
  },
  {
    id: 11,
    name: 'Benjamin Carter',
    email: 'benjamin.carter@example.com',
    status: 'Qualified',
    phone: '555-555-1234',
    currentCompany: 'Carter Technologies',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 8,
    skills: ['AWS', 'Node.js', 'Lambda'],
    resumeUrl: 'https://example.com/resume/benjamincarter.pdf',
  },
  {
    id: 12,
    name: 'Mia Nelson',
    email: 'mia.nelson@example.com',
    status: 'Rejected',
    phone: '555-555-8765',
    currentCompany: 'Nelson Corp',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 4,
    skills: ['Java', 'Spring', 'MongoDB'],
    resumeUrl: 'https://example.com/resume/mianelson.pdf',
  },
  {
    id: 13,
    name: 'Henry Evans',
    email: 'henry.evans@example.com',
    status: 'New',
    phone: '555-555-3210',
    currentCompany: 'Evans Innovations',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 3,
    skills: ['C#', '.NET', 'Azure'],
    resumeUrl: 'https://example.com/resume/henryevans.pdf',
  },
  {
    id: 14,
    name: 'Lily Turner',
    email: 'lily.turner@example.com',
    status: 'Rejected',
    phone: '555-555-4321',
    currentCompany: 'Turner Inc.',
    positionApplied: 'Software Engineer',
    yearsOfExperience: 5,
    skills: ['Python', 'Django', 'React'],
    resumeUrl: 'https://example.com/resume/lilyturner.pdf',
  },
];
